### ISSUE TITLE
How to use snapshot-gas-cost?

### ISSUE THREAD

**Issue by Bilidly** [Uniswap/universal-router#184]
Can't find documentation there https://github.com/Uniswap/snapshot-gas-cost

Gas cost of function do not show up in console when testing. How to test gas spending?

**Comment by marktoda** [comment]
Yarn test:gas

**Comment by Bilidly** [comment]
It's precisely what I mean: `yarn test:gas` won't display gas consumption of functions in the console. 
<img width="550" alt="Screenshot 2022-11-23 at 11 40 46 AM" src="https://user-images.githubusercontent.com/100553662/203470711-67e3cc2e-b492-4425-82d8-732ec7d3ac06.png">

**Comment by codeislight1** [comment]
you may find it in ./test/integration-tests/gas-tests/__snapshots__/ folder
if you really need to display it in console, try npm install hardhat-gas-reporter
https://www.npmjs.com/package/hardhat-gas-reporter

**Comment by Bilidly** [comment]
Thanks, found them files. Any recommendation how to view the content of .snap files (preferably without third party application) ?


FYI i tried gas-reporter but it won't properly recognize the test, so you'd get this:
<img width="779" alt="Screenshot 2022-11-23 at 3 49 46 PM" src="https://user-images.githubusercontent.com/100553662/203504667-cce54594-2294-420f-a043-5a2f569d60c3.png">

**Comment by ewilz** [comment]
your development editor should be be able to open snap files or even your browser. They shouldn't be more difficult to view than other files in your dev environment
