### ISSUE TITLE
NPM package cannot find Permit2 library

### ISSUE THREAD

**Issue by PowVT** [Uniswap/universal-router#186]
I installed the UR repo with this command `yarn add @uniswap/universal-router`. 

Then added the UniversalRouter.sol contract as an import into a contract to compile and generate its artifacts. 

The first error I see is `Error HH411: The library solmate, imported from @uniswap/universal-router/contracts/base/Dispatcher.sol, is not installed. Try installing it using npm`. I then installed solmate with yarn. Ran yarn compile again and had a similar issue with another of the submodules that the UR repo uses. Here is the error: `Error HH411: The library permit2, imported from @uniswap/universal-router/contracts/base/Dispatcher.sol, is not installed. Try installing it using npm` a Permit2 lib does not exist. 

Am I taking the right approach here? I feel like the submodules in the UR repo need to be updated to get past these errors, but am not sure how as I am using as a NPM package. Thanks!

yarn -v
`3.2.1`
node -v
`16.10.0`

**Comment by marktoda** [comment]
Thanks for reporting this! Forge/hardhat interop causing issues here as we need submodules internally to universal-router for solmate and permit2. I think the best bet is to add a postinstall script to universal-router that'll handle this automatically when you yarn install. We'll try to get something out fixing that today

**Comment by codeislight1** [comment]
running fixed it:
git submodule update --init --recursive

**Comment by PowVT** [comment]
Thanks all really appriciate the help. Still having the same issue. @codeislight1 this command produces and error which I screen shot below. 

![Screen Shot 2022-11-23 at 8 07 44 AM](https://user-images.githubusercontent.com/21206705/203554468-9288ae96-66a2-41c8-95b7-8ca47b87db07.png)

I have made sure there is a ssh key pair generated with this command `ssh-keygen -t ed25519 -C "myemail@xyz.com"`. And get the same error. Is this a permissions thing? thanks

**Comment by codeislight1** [comment]
i had a similar issue, you may fix it by downloading permit2 repo and
extract it within peemit2 folder, i believe that fixed it for me.

**Comment by PowVT** [comment]
Ya it worked for the Permit2 stuff, then starts erroring on the open-zeppelin submodule. So I did the same for that, extracted in to the OZ folder in the top level directory. Then I run `git submodule update --init --recursive` again and it gets past the permit2 and OZ stuff, but errors on the solmate submodule. Do I make a new folder for solmate similar to the other 2? Do this look like your file tree? Something feels off.

![Screen Shot 2022-11-23 at 8 30 50 AM](https://user-images.githubusercontent.com/21206705/203559100-43c0ee70-b5e8-42b4-9237-d2ae433fbbe9.png)

**Comment by PowVT** [comment]
here is the `yarn compile` error message: 
![Screen Shot 2022-11-23 at 8 34 07 AM](https://user-images.githubusercontent.com/21206705/203560007-e4db1496-d0f0-44b0-89e9-76c5ff8ebc21.png)

**Comment by codeislight1** [comment]
have you run yarn symlink? btw, when you paste the submodules manually,
paste them in folders under lib, then run yarn symlink, after that yarn
compile. this is as far i remember when i tried it last time.

**Comment by PowVT** [comment]
🙏 y'all are amazing, yup that was the key. Had to extract them into the `lib/permit2`, `lib/openzeppelin-contracts`, and `lib/solmate` folders. Then run `yarn symlink` like you said. Then yarn compile and test passed. Thanks.

I think the only stone left unturned is if I were to use this in another project's package.json and install via `yarn add @uniswap/universal-router`. The compiler still errors on those 3 packages. Solmate, OZ-contracts, and permit2 when I try to import and compile my project contracts. The first two I can install in my project, but Permit2 looks strictly a foundry repo, and cannot grab a package.json. Is this the right assumption? Would my route forward be to use it as a gitmodule as opposed to npm? Thanks again

**Comment by ewilz** [comment]
addressed in PR above. New release has instructions on integrating the repo that should hopefully make things easier.
