### ISSUE TITLE
Q: is there somewhere on chain where I can fetch the router and PERMIT2 addresses ?

### ISSUE THREAD

**Issue by clemsos** [Uniswap/universal-router#211]
I was wondering if there was a kind of Uniswap registry deployed somewhere as a contract where I could retrieve addresses for permit2 or universal router? 

That will allow my contract to track if the addresses change without having to pass them explicitely as param in the function or add it to the local storage of my contract. 

Many thanks !

**Comment by hensha256** [comment]
Hi! I'm afraid there is no registry of this on-chain. You can find all of the addresses for UniversalRouter deploys in [this folder](https://github.com/Uniswap/universal-router/tree/main/deploy-addresses). Permit2 is deployed at the same address on every chain - `0x000000000022D473030F116dDEE9F6B43aC78BA3`

**Comment by clemsos** [comment]
Thanks for the answer 👍
