### ISSUE TITLE
Consider returning amountOut / amountIn for exactIn / exactOut for swaps on v2 and v3

### ISSUE THREAD

**Issue by SolcAndMe** [Uniswap/universal-router#254]

**Comment by hensha256** [comment]
The design of the contract currently does not support a way to select and abstract return values from sub-calls. If you are integrating and need to know the number of tokens received I would recommend performing balance checks - this would also protect you against fee on transfer tokens.

**Comment by lispking** [comment]
This balanceOf method is not suitable as there may have been other balances before.
