### ISSUE TITLE
UniversalRouter vs UniversalRouterV1_2

### ISSUE THREAD

**Issue by Florian-S-A-W** [Uniswap/universal-router#311]
As far as I understand, the only difference between the UniversalRouter and UniversalRouterV1_2 contracts is that the critical vulnerability mentioned [here](https://dedaub.com/blog/uniswap-bug-bounty) was fixed.

Users should always use the new version, but the difference is not documented anywhere. I noticed new projects still using the old router.

I think it would make sense to add a note in the project README, a comment in the deployment address files, or both.

**Comment by ewilz** [comment]
There's not critical vulnerabiliy there. It's misinformation from etherscan and dedaub.
