### ISSUE TITLE
Why exactInputSingle did not return amoutOut?

### ISSUE THREAD

**Issue by lispking** [Uniswap/universal-router#312]
The exactInputSingle method did not return the quantity of currency exchanged, making it inconvenient to use in other contracts. When will this value be opened?
like this: https://github.com/Uniswap/v3-periphery/blob/v1.0.0/contracts/SwapRouter.sol#L87

**Comment by hensha256** [comment]
this contract does not have a function called `exactInputSingle`. It works with commands that cannot return values currently. For now I recommend using a difference in token balances to find this value - this will help you support fee on transfer tokens too.
