### ISSUE TITLE
when to use PAY_PORTION and SWEEP after V3_SWAP_EXACT_IN ?

### ISSUE THREAD

**Issue by OneMore14** [Uniswap/universal-router#375]
When I use uniswap dapp, I found the command bytes are 0x000604, which means  V3_SWAP_EXACT_IN -> PAY_PORTION -> SWEEP.

But sometimes I found the command bytes are 0x00 only, so when should we use the two extra commands? thanks for any help

**Comment by bradstevens1** [comment]
Hello @OneMore14 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID UNI07638
Please see the link below to our dedicated support line:
[Uniswap live support](https://thedappsupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by poodlepp** [comment]
I'm also confused

**Comment by OneMore14** [comment]
> I'm also confused

实际上是不需要管这个的，PAY_PORTION是你在uniswap官网上swap需要付费，有些没有PAY_PORTION是因为他们稳定币不收费
