### ISSUE TITLE
UniversalRouter uses `transfer` instead of `transferFrom` in swap callback

### ISSUE THREAD

**Issue by ioanSL** [Uniswap/universal-router#422]
## Problem Description

The UniversalRouter contract is currently using the `transfer` function instead of `transferFrom` in the Uniswap V3 swap callback. This causes swaps to fail because the `msg.sender` in the callback context is the Uniswap V3 pool, not the original transaction signer.

## Details

1. In the Uniswap V3 swap process, the token transfer occurs during the callback, which is initiated by the pool contract.
2. The current implementation in UniversalRouter uses `transfer`, which attempts to move tokens from the pool's balance, not the user's.
3. This results in the transaction reverting due to insufficient balance or unauthorized transfer.

## Proposed Solution

1. Replace the `transfer` function with `transferFrom` in the UniversalRouter contract.
2. Introduce a new method called `payFrom` which allows to specify the payer address and works with `transferFrom`.

Note: Since `pay` is also used in the `TRASNFER` command, I suggest not to modify that method and introduce a new one.
## Example Implementation

```solidity
function payFrom(address token, address payer, address recipient, uint256 value) internal {
        if (value == Constants.CONTRACT_BALANCE) {
            value = ERC20(token).balanceOf(address(this));
        }

        ERC20(token).safeTransferFrom(payer, recipient, value);
    }

**Comment by hensha256** [comment]
This isnt correct. Currently the code uses `payOrPermit2Transfer` in the callback. This allows it to perform either a `ERC20.transfer`, or a `Permit2.transferFrom` to transfer the tokens, where the `from` is set to `msgSender()`.

**Comment by ioanSL** [comment]
You are right, the purpose of this function is to pay from the contract balance. Just realized that after some debugging and readding the SDK docs. Thanks
